### ISSUE TITLE
Underscores not converted correctly

### ISSUE THREAD

**Issue by veggiedefender** [ellipticaldoor/get-color-by-text#2]
Since you replace spaces with _ in the URL if I enter something like `_ _ ___ _` and share the [link](https://ellipticaldoor.com/get-color-by-text/#/?q=_________), it's just a bunch of spaces. In fact, all underscores get converted to spaces.

URL encoding the "normal" way instead of your own custom way might be better for this.

#3 fixes this.

**Comment by ellipticaldoor** [comment]
Thanks! I didn't noticed this.

I found that the vue router automatically converts the text to a valid url so now multiple underscores and spaces are supported.
